### ISSUE TITLE
I'm getting an error parsing messages

### ISSUE THREAD

**Issue by mirosval** [gilbertw1/slack-scala-client#43]
```scala
[SlackRtmClient] Error reading event: {"type":"desktop_notification", ... [truncated] ... }
[info] play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List(Invalid type property: {}),WrappedArray(desktop_notification))))))
[info] 	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
[info] 	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
[info] 	at play.api.libs.json.JsResult$class.fold(JsResult.scala:67)
[info] 	at play.api.libs.json.JsError.fold(JsResult.scala:12)
[info] 	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
[info] 	at play.api.libs.json.JsObject.as(JsValue.scala:92)
[info] 	at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1$$anonfun$13.apply(SlackRtmClient.scala:112)
[info] 	at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1$$anonfun$13.apply(SlackRtmClient.scala:112)
[info] 	at scala.util.Try$.apply(Try.scala:192)
[info] 	at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.applyOrElse(SlackRtmClient.scala:112)
[info] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
[info] 	at slack.rtm.SlackRtmConnectionActor.aroundReceive(SlackRtmClient.scala:95)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

It does not seem to affect the functioning of the library, there are no crashes and everything still works, but this shows up in the console.

**Comment by asheshambasta** [comment]
Same here.

**Comment by gilbertw1** [comment]
Thanks for reporting, this has just been fixed in 69dc64dd268745db25985cc8f28bc39c2d6bbae2. I plan on pushing out an update today.

**Comment by asheshambasta** [comment]
thanks @gilbertw1

**Comment by asheshambasta** [comment]
I'm still seeing SBT resolve errors for `0.2.1`. Any ETA on this?

**Comment by gilbertw1** [comment]
Hey, just released a few minutes ago. Will probably take a few hours to propogate to maven central.
